[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autoappraiser"
version = "1.0.0"
description = "Auto Appraiser for Roblox Fisch"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
]
dependencies = [
    "customtkinter",
    "mss",
    "keyboard",
    "Pillow",
    "tomlkit",
    "opencv-python",
    "numpy",
    "rapidfuzz",
    "pytesseract"
]

[project.optional-dependencies]
windows = [
    "dxcam_cpp",
    "pydirectinput",
    "winrt-runtime",
    "winrt-Windows.Graphics.Imaging",
    "winrt-Windows.Media.Ocr",
    "winrt-Windows.Storage.Streams",
    "winrt-Windows.Foundation"
]

linux = [
    "pyautogui",
    "pynput"
]

[project.scripts]
autoappraiser = "autoappraiser.__main__:main"

[tool.setuptools]
packages = ["autoappraiser"]
