name: Push

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[windows]"

      - name: Build
        uses: nuitka/nuitka-action@main
        with:
          nuitka-version: 'main'
          script-name: 'autoappraiser'
          mode: 'onefile'
          clang: 'on'
          lto: 'yes'
          enable-plugins: tk-inter
          windows-icon-from-ico: 'autoappraiser/res/icon.ico'
          include-package: 'winrt'
          include-data-dir: 'autoappraiser/res=autoappraiser/res'
          output-file: 'AutoAppraiser-debug.exe'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoAppraiser-windows-debug
          path: build/AutoAppraiser-debug.exe

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          apt update
          apt install -y gcc wget tar xz-utils libgl1-mesa-dev libglib2.0-0 libx11-dev libx11-xcb1 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0 libsqlite3-0 libgdbm6 libreadline8 libncursesw6 linux-libc-dev libc6-dev patchelf tk-dev tcl-dev tesseract-ocr

      - name: Setup clang
        run: |
          wget https://github.com/Moon-Playground/tc-build/releases/download/21.1.8-2078da43e/Mayuri-clang_21.1.8-bookworm-x86_64-2078da43e.tar.xz
          tar -xvf Mayuri-clang_21.1.8-bookworm-x86_64-2078da43e.tar.xz -C /usr/local

      - name: Setup python
        run: |
          wget https://github.com/Moon-Playground/Python-builder/releases/download/python-v3.13.11/python-3.13.11-debian-bookworm-x86_64.deb
          dpkg -i python-3.13.11-debian-bookworm-x86_64.deb || apt install -y -f

      - name: Install dependencies
        run: |
          /opt/python3.13/bin/python3.13 -m ensurepip
          /opt/python3.13/bin/python3.13 -m pip install --upgrade pip
          CC=/usr/local/bin/clang CXX=/usr/local/bin/clang++ \
          /opt/python3.13/bin/python3.13 -m pip install ".[linux]"

      - name: Setup Nuitka
        run: |
          /opt/python3.13/bin/python3.13 -m pip install -U "https://github.com/Nuitka/Nuitka/archive/main.zip"
          /opt/python3.13/bin/python3.13 -m pip install zstandard

      - name: Build
        run: |
          mkdir -p build
          CC=/usr/local/bin/clang CXX=/usr/local/bin/clang++ LDFLAGS="-fuse-ld=lld" \
          /opt/python3.13/bin/python3.13 -m nuitka \
            --onefile \
            --lto=yes \
            --enable-plugin=tk-inter \
            --include-data-dir=autoappraiser/res=res \
            --output-dir=build \
            --output-filename=AutoAppraiser-debug \
            --deployment \
            --python-flag=no_docstrings \
            --remove-output \
            autoappraiser

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoAppraiser-linux-debug
          path: build/AutoAppraiser-debug
